// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorData.Shared
{
    public partial class PayloadDBData
    {
        public PayloadDBData()
        {
            SubData = new HashSet<SubData>();
        }

        public Guid Id { get; set; }
        public string DeviceId { get; set; }
        public string DeviceType { get; set; }
        public string DeviceName { get; set; }
        public string GroupId { get; set; }
        public string DataType { get; set; }
        public DateTime? Timestamp { get; set; }
        public string UserName { get; set; }

        public virtual ICollection<SubData> SubData { get; set; }
    }
}