// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorData.Server.Models;

namespace BlazorData.Server.Data
{
    public partial class BlazorDBContext : DbContext
    {
        public BlazorDBContext()
        {
        }

        public BlazorDBContext(DbContextOptions<BlazorDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PayloadData> PayloadData { get; set; }
        public virtual DbSet<SubData> SubData { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PayloadData>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.DataType).HasMaxLength(50);

                entity.Property(e => e.DeviceId).HasMaxLength(50);

                entity.Property(e => e.DeviceName).HasMaxLength(50);

                entity.Property(e => e.DeviceType).HasMaxLength(50);

                entity.Property(e => e.GroupId).HasMaxLength(50);

                entity.Property(e => e.Timestamp).HasColumnType("datetime");

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<SubData>(entity =>
            {
                entity.HasKey(e => e.DataId)
                    .HasName("PK__SubData__9D05303D22138CEE");

                entity.Property(e => e.DataId).ValueGeneratedNever();

                entity.Property(e => e.Name).HasMaxLength(200);

                entity.Property(e => e.Pid).HasColumnName("PId");

                entity.Property(e => e.Value).HasMaxLength(200);

                entity.HasOne(d => d.PidNavigation)
                    .WithMany(p => p.SubData)
                    .HasForeignKey(d => d.Pid)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__SubData__PId__5441852A");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}